apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fineract-activemq
  labels:
    app: fineract-activemq
spec:
  selector:
    matchLabels:
      app: fineract-activemq
  replicas: {{ .Values.fineractactivemq.replicaCount }}
  serviceName: fineract-activemq
  template:
    metadata:
      labels:
        app: fineract-activemq
    spec:
      containers:
      - name: fineract-activemq
        image: {{ .Values.fineractactivemq.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy}}
        ports:
        - name: http
          containerPort: 8161
        - name: core
          containerPort: 61616
        - name: amqp
          containerPort: 5672
        envFrom:
        - configMapRef:
            name: fineract-activemq-configmap
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: core
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 3