{{- if .Values.fineractrest.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.commonconfig.FINERACT_REST_BACKEND_DOMAIN | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "fineract.rest.fullname" . }}
                port:
                  number: 8080
  tls:
    - hosts:
        - {{ .Values.commonconfig.FINERACT_REST_BACKEND_DOMAIN | quote }}
      secretName: {{ .Values.ingress.tls_secret }}
{{- end -}}