{{- if and .Values.ingress.enabled .Values.fineractreport.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
    - host: {{ .Values.commonconfig.FINERACT_REPORT_DOMAIN | quote }}
      http:
        paths:
          - path: /fineract-provider
            pathType: Prefix
            backend:
              service:
                name: {{ template "fineract.report.fullname" . }}
                port:
                  number: 8443
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "fineractreportUI.fullname" . }}
                port:
                  number: 443
  tls:
    - hosts:
        - {{ .Values.ingress.wildcard | quote }}
      secretName: {{ .Values.ingress.tls_secret }}
{{- end -}}
