{{- if and .Values.fineractjob.enabled .Values.ingress.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: fineract-job-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.commonconfig.FINERACT_JOB_DOMAIN | quote }}
      http:
        paths:
          - path: /fineract-provider
            pathType: Prefix
            backend:
              service:
                name: {{ template "fineract.job.fullname" . }}
                port:
                  number: 8443
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "fineractjobUI.fullname" . }}
                port:
                  number: 443
  tls:
    - hosts:
        - {{ .Values.ingress.wildcard | quote }}
      secretName: {{ .Values.ingress.tls_secret }}
{{- end -}}
