{{- if and .Values.fineractrest.enabled .Values.ingress.enabled -}}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"
spec:
  rules:
    - host: {{ .Values.commonconfig.FINERACT_REST_DOMAIN | quote }}
      http:
        paths:
          - path: /fineract-provider
            pathType: Prefix
            backend:
              serviceName: {{ template "fineract.rest.fullname" . }}
              servicePort: 8443
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ template "fineractrestUI.fullname" . }}
              servicePort: 443
  tls:
    - hosts:
        - {{ .Values.ingress.wildcard | quote }}
      secretName: {{ .Values.ingress.tls_secret }}
{{- end -}}