{{ if .Values.fineractjob.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fineractjobUI.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: fineract-job-ui
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
  selector:
    app: fineract-job-ui
    tier: frontend
    instance: {{ .Release.Name }}
{{- end -}}