{{ if and .Values.fineractrest.enabled .Values.fineractrestUI.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fineractrestUI.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: fineract-rest-ui
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
  selector:
    app: fineract-rest-ui
    tier: frontend
    instance: {{ .Release.Name }}
{{- end -}}
