{{- if and .Values.fineractrest.ingress.enabled .Values.fineractrestUI.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.commonconfig.FINERACT_REST_DOMAIN | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "fineractrestUI.fullname" . }}
                port:
                  number: 8080
  tls:
    - hosts:
        - {{ .Values.commonconfig.FINERACT_REST_DOMAIN | quote }}
      secretName: {{ .Values.ingress.tls_secret }}
{{- end -}}